AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
    Default: up.dabase.com
  ACMCertificateArn:
    Type: String
  Password:
    Type: String
    NoEcho: true
  Bucket:
    Type: String
    Default: s.natalian.org

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Resources:
  AccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName: !Ref DomainName

  Gateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref ACMCertificateArn

  UploadTopic:
    Type: AWS::SNS::Topic

  NotifyTopic:
    Type: AWS::SNS::Topic

  NotifyTopicEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: hendry+s3postprocessed@iki.fi
      TopicArn: !Ref NotifyTopic

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Environment:
        Variables:
          PASSWORD: !Ref Password
          BUCKET: !Ref Bucket
          NOTIFY_TOPIC: !Ref UploadTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt UploadTopic.TopicName
        - S3WritePolicy:
            BucketName: !Ref Bucket
      Events:
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /
            Method: GET
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: makefile

  TranscodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 300
      MemorySize: 10240
      Environment:
        Variables:
          TOPIC: !Ref NotifyTopic
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Bucket
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotifyTopic.TopicName
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref UploadTopic
    Metadata:
      BuildMethod: makefile

Outputs:
  CNAME:
    Description: CNAME value for DNS — point up.dabase.com here
    Value: !GetAtt [Gateway.DomainName, RegionalDomainName]
